# mongo-secure/Dockerfile
FROM mongo:latest

# Copy keyfile to image
COPY secrets/mongodb-keyfile /etc/mongo-keyfile

# Set permissions
RUN chmod 400 /etc/mongo-keyfile && \
    chown mongodb:mongodb /etc/mongo-keyfile

# Set default command to enable auth and replica set
CMD ["mongod", "--replSet", "rs0", "--bind_ip_all", "--auth", "--keyFile", "/etc/mongo-keyfile"]


