services:

  mongodb:
    build:
      context: .
      dockerfile: dockerfile_cluster
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mydata:/data/db/
      - ./mylogs:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

  mongodb2:
    build:
      context: .
      dockerfile: dockerfile_cluster
    container_name: mongodb2
    hostname: mongodb2
    volumes:
      - ./mydata2:/data/db/
      - ./mylogs2:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster

  mongodb3:
    build:
      context: .
      dockerfile: dockerfile_cluster
    container_name: mongodb3
    hostname: mongodb3
    volumes:
      - ./mydata3:/data/db/
      - ./mylogs3:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge

# volumes:
#   mysql_data:
#     driver: local

# mongo-express:
#   image: mongo-express:latest
#   container_name: mongo-express
#   restart: always
#   environment:
#     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#     ME_CONFIG_MONGODB_PORT: 27017
#     ME_CONFIG_MONGODB_SERVER: 'mongodb'
#     ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
#     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
#   ports:
#     - 8081:8081
#   networks:
#     - mongodb_network
#   depends_on:
#     - mongodb
# volumes:
#   mongodb-data:
#     driver: local
#     name: mongo-data
#   mongodb-log:
#     driver: local
#     name: mongo-log

# networks:
#   mongodb_network:
#     driver: bridge
#     name: mongo-network

